number = int(input("Введите целое число: "))
decimal = float(input("Введите десятичное число: "))
line_1 = input("Введите строку 1: ")
line_2 = input("Введите строку 2: ")
print("Были введены: \n   числа: ", number, " и ", decimal, "\n   строка 1: ", line_1, "\n   строка 2: ", line_2)
